### ISSUE TITLE
Exclude Certain Types

### ISSUE THREAD

**Issue by graywolf336** [ldez/tagliatelle#10]
We need a way to exclude certain types so we don't have to continuously disable this linter on that line. I would love regex support or something similar. For example, working with mongo, the default ID field is `_id`.

**Comment by georgettica** [comment]
in addition, somethimes `yaml` has wierdly formatted inputs
```
type objName struct {
        Event struct {
                EventType  string    `yaml:"event_type"`
                OccurredAt time.Time `yaml:"occurred_at"`
        } `yaml:"event"`
}
```

```
main.go:XXX : json(camel): got 'event_type' want 'eventType' (tagliatelle)
```

**Comment by vsachs** [comment]
Plus one to this issue, sometimes as a consumer of a 3rd party API we don't have control over the naming of the field but would like to use consistent naming internally.

**Comment by ldez** [comment]
related to #3, I need to finish my work on that.
