### ISSUE TITLE
tagliatelle: issue with invalid struct

### ISSUE THREAD

**Issue by ccoVeille** [ldez/tagliatelle#11]
Tagliatelle is unable to detect issue with invalid tags

```
// MessedUpTags is to validate structtag validation is done
// without it, the tool could let think everything is ok, while it's not.
type MessedUpTags struct {
	// an invalid tag listed in the rule is supported.
	Bad string `json:"bad` // want "struct field tag `json:\"bad` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"

	// an invalid tag not in the rule is supported.
	Whatever string `foo:whatever` // want "struct field tag `foo:whatever` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"

	// a invalid tag supported by the rule, is not hidden by another broken tag
	Mixed string `json:"mixed" foo:mixed` // want "struct field tag `json:\"mixed\" foo:mixed` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"
}
```

**Comment by ccoVeille** [comment]
I worked on a fix, I'm about to publish.

**Comment by ldez** [comment]
Hello,

the goal tagliatelle is not to validate struct tags, there are already linters that manage that.

**Comment by ccoVeille** [comment]
I agree with you, but it failed to validate an issue with the following code (example)

```
type Foo struct {
Mixed `json:"mixe" yaml:"mixed` // here the ending quote is missing
}
```

For me this, this is a legitimate use cases.

tagliatelle may not return information about what the problem is, but I think it should at least report, it cannot analyze the tag.

Because otherwise, it reports there is no problem at all with such a structure

**Comment by ldez** [comment]
In your example, tagliatelle will find the problem with JSON tag.

```
json(camel): got 'mixe' want 'mixed'
```

```go
type Mixed struct{}

type Foo struct {
	Mixed `json:"mixe" yaml:"mixed`
}
```

Note: in this case, the tag `yaml` is useless because YAML parser use `json` tag by default.

---

But in the following example, the struct tag will be "ignore":

```go
type Mixed struct{}

type Foo struct {
	Mixed `json:"mixe`
}
```

**Comment by ldez** [comment]
> but I think it should at least report, it cannot analyze the tag.

The reflect API doesn't allow us to see a difference between a missing tag or a malformed tag.

**Comment by ccoVeille** [comment]
Yes, I use it locally via golang-ci, also tagliatelle.

It's just that I installed tagliatelle directly, and failed to detect something, while doing my tests.

I agree with you and the need to keep your linter simple, so I will close this MR, and the issue, but I will open a new MR to document tagliatelle is not about validating struct, and that structtag is the perfect candidate to do that.
