### ISSUE TITLE
feature: forward to strcase customization

### ISSUE THREAD

**Issue by gabyx** [ldez/tagliatelle#26]
It would be really nice if we can forward settings to 

https://github.com/ettle/strcase/blob/main/README.md#customization

and rewrite the caser such that it would use this.
Would you welcome a PR?

**Comment by ldez** [comment]
I think that providing the full configuration is too complex to be usable within a configuration.

I also think only the initialism elements are interesting as a configuration.
Related to #19 and #2.

What is your use case behind this issue?

**Comment by gabyx** [comment]
Basically we would like to have 
custom lints: e.g. "mongoDB" is not in the list which strcase will convert to "mongoDb" which is conflicting with `stylecheck` etc.

So a way to configure exceptions by leveraging the full caser customization in strcase would help.

**Comment by ldez** [comment]
So you don't need all the options related to the caser customization but just initialisms options.
