### ISSUE TITLE
snake style

### ISSUE THREAD

**Issue by francisLee777** [ldez/tagliatelle#5]
![image](https://user-images.githubusercontent.com/30818378/141229086-838dcc71-bc14-4529-a233-64e81e49f6d0.png)
I want to use snake style， but the linter always suggest to me use camel

**Comment by ldez** [comment]
The standalone linter is restricted, if you want to use the full possibilities you have to use this linter through golangci-lint. https://golangci-lint.run/usage/linters/#tagliatelle
