### ISSUE TITLE
tagliatelle now warns on inline struct fields

### ISSUE THREAD

**Issue by silverlyra** [ldez/tagliatelle#8]
Since 7b219253661560e60d284e3cddfb912dc49862fc, structs with `json:",inline"` fields now prompt a warning from tagliatelle that a name should be given in the expected camelCase.

I think this is incorrect behavior as there is no field name for an `inline` struct.

**Comment by ldez** [comment]
Hello,

currently, tagliatelle is format neutral, so `inline` is not interpreted.

I need to think about how to about that.

Ref: https://github.com/ldez/tagliatelle/issues/6

**Comment by ldez** [comment]
I see your PR, it's an opinionated approach because it's not following a neutral format.

**Comment by silverlyra** [comment]
Hi,

> currently, tagliatelle is format neutral, so inline is not interpreted.

I understand where you’re coming from. The latest tagliatelle is included in [the latest golanglint-ci](https://github.com/golangci/golangci-lint/releases/tag/v1.44.0), so all projects that use golanglint-ci, have tagliatelle enabled, and use `json:",inline"` fields are now going to have false positive lint errors.

This package already can’t process `xml` struct tags correctly, as that can encode parent tags like `xml:"child>plant"`. I'd recommend moving away from this format-neutral approach. I'll roll back the golanglint-ci version we're using for now, but a fix is needed here.

**Comment by ldez** [comment]
> I'd recommend moving away from this format-neutral approach.

It's a bit more complex: currently, you can define any struct tag, so it must be "neutral" or at least configurable.

> This package already can’t process xml struct tags correctly,

This is interesting, maybe you can open another on this topic.

**Comment by silverlyra** [comment]
> > This package already can’t process xml struct tags correctly,
> 
> This is interesting, maybe you can open another issue on this topic.

It's not an issue that affects my directly. I'm saying that, while you've been thinking tagliatelle is format-neutral, I think it’s actually only compatible with struct tags that are compatible with `json` tags. So I don't think scanning for `,inline` is as big of a departure from the current behavior as you do.

**Comment by ldez** [comment]
a small note:

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

type Foo struct {
	Bar Bar `json:",inline"`
}

type Bar struct {
	Name string `json:"name"`
}

func TestName(t *testing.T) {
	f := &Foo{Bar: Bar{Name: "goo"}}
	fmt.Println(json.NewEncoder(os.Stdout).Encode(f))
}
// {"Bar":{"name":"goo"}}
// <nil>

```


```go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

type Foo struct {
	Bar `json:",inline"`
}

type Bar struct {
	Name string `json:"name"`
}

func TestName(t *testing.T) {
	f := &Foo{Bar: Bar{Name: "goo"}}
	fmt.Println(json.NewEncoder(os.Stdout).Encode(f))
}

// {"name":"goo"}
// <nil>
```

The `inline` option can hide some cases if the tag is wrongly configured.

It's not a real argument but just a note.

**Comment by ldez** [comment]
So I'm not happy with this decision but I will follow you.

In the future, I will rewrite tagliatelle to handle tag with a less neutral approach.

FYI I'm also a maintainer of golangci-lint.

**Comment by ldez** [comment]
After more research, in fact, `inline` is not supported by the [json encoder](https://github.com/golang/go/issues/6213).

The "inline" effect is produced by the empty value.

But `inline` inside the `json` tag is used by YAML encoder...

The encoders don't follow the same specification but they overuse the `json` tags... :cry:

**Comment by seaneagan** [comment]
here's the workarond that I'm currently using:

```
issues:
  exclude-rules:
    # Workaround: https://github.com/ldez/tagliatelle/issues/8
    - source: \`json:"(,inline)?"
      linters:
        - tagliatelle
```
